# Generated by Django 5.2.3 on 2025-06-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs/'),
        ),
    ]
