# Generated by Django 5.2.3 on 2025-06-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0002_book_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
