# Generated by Django 5.2.3 on 2025-06-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0003_remove_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
    ]
