# Generated by Django 5.2.3 on 2025-06-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0005_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
