# Generated by Django 5.2.3 on 2025-06-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0010_alter_blogcomment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_admin.book'),
        ),
    ]
