# Generated by Django 5.2.3 on 2025-06-16 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0011_alter_bookreview_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='library_admin.article'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_admin.book'),
        ),
        migrations.CreateModel(
            name='BookReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='library_admin.bookreview')),
            ],
        ),
    ]
