# Generated by Django 5.2.3 on 2025-06-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0013_bookcomment_newscomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('blog', 'Blog'), ('book', 'Book'), ('bookreview', 'Book Review'), ('news', 'News')], max_length=20)),
                ('comment_id', models.IntegerField()),
                ('reply', models.TextField()),
                ('admin_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
