# Generated by Django 5.2.3 on 2025-06-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0016_auto_category_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
