# Generated by Django 5.2.3 on 2025-06-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0018_sitevisit_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('blog', 'Blog'), ('book', 'Book'), ('review', 'Book Review'), ('news', 'News')], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('object_title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteVisit',
        ),
    ]
