# Generated by Django 5.2.3 on 2025-06-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0020_userprofile_delete_comment_blogcomment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookreviewcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newscomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
