# Generated by Django 5.2.3 on 2025-06-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0023_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
