# Generated by Django 5.2.3 on 2025-06-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0025_historicalarticle_historicalblogcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
