# Generated by Django 5.2.3 on 2025-06-29 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0027_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='library_admin.blogcomment'),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='library_admin.bookcomment'),
        ),
        migrations.AddField(
            model_name='bookreviewcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='library_admin.bookreviewcomment'),
        ),
        migrations.AddField(
            model_name='historicalblogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='library_admin.blogcomment'),
        ),
        migrations.AddField(
            model_name='historicalbookcomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='library_admin.bookcomment'),
        ),
        migrations.AddField(
            model_name='historicalbookreviewcomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='library_admin.bookreviewcomment'),
        ),
        migrations.AddField(
            model_name='historicalnewscomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='library_admin.newscomment'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='library_admin.newscomment'),
        ),
    ]
