# Generated by Django 5.2.3 on 2025-06-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0028_blogcomment_parent_bookcomment_parent_and_more'),
    ]

    operations = [
    ]
