# Generated by Django 5.2.3 on 2025-06-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0030_blogcomment_is_active_bookcomment_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
