# Generated by Django 5.2.3 on 2025-06-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0032_alter_commentreply_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
