# Generated by Django 5.2.3 on 2025-07-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0034_alter_blogcomment_rating_alter_bookcomment_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='HistoricalKeyword',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
