# Generated by Django 5.2.3 on 2025-07-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0035_remove_article_keywords_delete_historicalkeyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='historicalbookreview',
            name='rating',
        ),
    ]
