# Generated by Django 5.2.3 on 2025-07-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0036_remove_bookreview_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='views',
        ),
        migrations.RemoveField(
            model_name='historicalbook',
            name='views',
        ),
    ]
