# Generated by Django 5.2.3 on 2025-07-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0038_alter_book_category_alter_historicalbook_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('blog', 'Blog/Article'), ('news', 'News')], default='book', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('blog', 'Blog/Article'), ('news', 'News')], default='book', max_length=20),
        ),
    ]
