# Generated by Django 5.2.3 on 2025-07-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0040_alter_historicalnews_category_alter_news_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnews',
            name='views',
        ),
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
    ]
