# Generated by Django 5.2.3 on 2025-07-02 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('library_admin', '0043_remove_historicalblogcomment_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='parent_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='parent_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
