# Generated by Django 5.2.3 on 2025-07-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_admin', '0044_commentreply_parent_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='parent_object_id',
        ),
    ]
