# Generated by Django 5.2.3 on 2025-07-02 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_blogcomment_parent_remove_bookcomment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent_object_id',
        ),
        migrations.RemoveField(
            model_name='bookcomment',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='bookcomment',
            name='parent_object_id',
        ),
        migrations.RemoveField(
            model_name='bookreviewcomment',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='bookreviewcomment',
            name='parent_object_id',
        ),
        migrations.RemoveField(
            model_name='historicalblogcomment',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='historicalblogcomment',
            name='parent_object_id',
        ),
        migrations.RemoveField(
            model_name='historicalbookcomment',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='historicalbookcomment',
            name='parent_object_id',
        ),
        migrations.RemoveField(
            model_name='historicalbookreviewcomment',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='historicalbookreviewcomment',
            name='parent_object_id',
        ),
        migrations.RemoveField(
            model_name='historicalnewscomment',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='historicalnewscomment',
            name='parent_object_id',
        ),
        migrations.RemoveField(
            model_name='newscomment',
            name='parent_content_type',
        ),
        migrations.RemoveField(
            model_name='newscomment',
            name='parent_object_id',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.blogcomment'),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.bookcomment'),
        ),
        migrations.AddField(
            model_name='bookreviewcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.bookreviewcomment'),
        ),
        migrations.AddField(
            model_name='historicalblogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comments.blogcomment'),
        ),
        migrations.AddField(
            model_name='historicalbookcomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comments.bookcomment'),
        ),
        migrations.AddField(
            model_name='historicalbookreviewcomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comments.bookreviewcomment'),
        ),
        migrations.AddField(
            model_name='historicalnewscomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comments.newscomment'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.newscomment'),
        ),
    ]
