# Generated by Django 5.2.3 on 2025-07-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_blogcomment_parent_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='parent_is_admin_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='parent_is_admin_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookreviewcomment',
            name='parent_is_admin_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalblogcomment',
            name='parent_is_admin_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbookcomment',
            name='parent_is_admin_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbookreviewcomment',
            name='parent_is_admin_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalnewscomment',
            name='parent_is_admin_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='parent_is_admin_reply',
            field=models.BooleanField(default=False),
        ),
    ]
