# Generated by Django 5.2.3 on 2025-07-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0006_userprofile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
